database:
  host: localhost:27017
  name: database
  env: native
  user: ######
  password: ######

redis:
  enable: true
  host: localhost
  port:
  password:
  database: 0

cache:
  enable: true
  expiry_time: 3600

jwt_auth:
  signing_key: access
  expired: 900
  signing_refresh_key: refresh
  expired_refresh_token: 1
